apiVersion: v1
kind: ConfigMap
metadata:
  name: task-queue-config
  namespace: task-queue
data:
  DB_HOST: "postgresql.task-queue.svc.cluster.local"
  DB_PORT: "5432"
  DB_USERNAME: "taskqueue"
  DB_DATABASE: "taskqueue"
  DB_SSL_MODE: "disable"
