apiVersion: v1
kind: Service
metadata:
  name: task-queue-server
  namespace: task-queue
spec:
  type: NodePort
  selector:
    app: task-queue-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
